# Site wide configuration

title: Academic Website of David Izydorczyk
locale: en_US


# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: David Izydorczyk
  avatar: profile_pic.jpg
  bio: "This is a sample Jekyll academic website."
  email: izydorczyk@uni-mannheim.de
  twitter: easydoorchick
