title:		           'David Izydorczyk'
description:	       'David Izydorczyk, PhD Student'
author:              'David Izydorczyk'

# Enter the following platform usernames if you would like for them to appear on your site.
owner:
  name: David Izydorczyk
  avatar: profile_pic.jpg
  bio: "This is a sample Jekyll academic website."
  email: izydorczyk@uni-mannheim.de
  twitter: easydoorchick


# Build settings
markdown:            kramdown
highlighter:         rouge
permalink:           none
plugins:             [jekyll-paginate, jekyll-sitemap, jekyll-feed, jekyll-seo-tag]

