project:
  type: website
  output-dir: docs

website:
  title: "David Izydorczyk"
  reader-mode: true

  navbar:
    background: dark
    search: true
    left:
      - pages/cv.qmd
      - pages/publications.qmd
      - pages/teaching.qmd
      - text: "Blog"
        href: blog/index.qmd
      - pages/shiny.qmd
  page-footer: 
    left: "Copyright 2021, David Izydorczyk" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 



format:
  html:
    theme: 
      dark: darkly
      light: cosmo 
    css: styles.css
    toc: true
    linkcolor: "#5381e6"



