project:
  type: website
  output-dir: docs

website:
  title: "David Izydorczyk"
  reader-mode: true

  navbar:
    background: dark
    search: true
    left:
      - href: pages/index.qmd
        text: "Home"
      - pages/cv.qmd
      - pages/publications.qmd
      - pages/teaching.qmd
      - pages/shiny.qmd
  page-footer: 
    left: "Copyright 2021, Norah Jones" 
    right: 
      - icon: github
        href: https://github.com/
      - icon: twitter 
        href: https://twitter.com/ 



format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



