---
title: "Teaching"
---

<br>

## Workshops (PhD level)


[**Workshop Modern R**](https://github.com/dizyd/Workshop_ModernR): This workshop teaches the basics of R Markdown and how to write APA conform manuscripts using R Markdown and the `papaja`-package. In addition, it will give an introduction into building interactive web applications in R with `shiny`. 


[**Workshop Advanced R**](https://github.com/dizyd/Workshop_AdvancedR): This workshop shows how to benchmark and profile functions in R to identify potential bottlenecks. The workshops then also shows how to  solve those bottlenecks and speed up your R code through vectorized R code, Rcpp, or parallelization.

## Seminars (Bachelor)


**General Psychology II**: Topics: Cognitive Illusions.


**Project Seminar Experimental Psychology**: In this seminar, students plan, conduct, and present their own research project in small groups. Projects supervised so far: 

- Wie beeinflusst die Berichterstattung über Corona das Entscheidungsverhalten? 
- Framing Effekt in Zeiten einer Pandemie: Krankheit oder Risiko?
