---
title: "CV"
classoption: .column-page

---


## <i class="bi bi-mortarboard-fill"></i> Education


**Doctoral (Ph.D.) Candidate in Psychology** , University of Mannheim, since 10/2016,  
Doctoral program at the DFG Research Training Group “Statistical Modeling in Psychology” (SMiP) (supervisors: Arndt Bröder, Benjamin Hilbig, Jeff Rouder)

**M.Sc. Psychology**, University of Cologne, 10/2016-09/2018, research-oriented psychology with specializations in cognitive psychology, media psychology, and neuroscience. Thesis: _Simulating the ecology: Using the BIAS model to simulate and explain contradicting evidence of the out-group homogeneity effect, the intergroup bias, and the density hypothesis_  (advisors: Christian Unkelbach, Jan Peters)

**B.Sc. Psychology**, University of Koblenz-Landau, 10/2012-09/2016.
Thesis: _Structuring the uncanny valley: Investigating the effect of the personal need for structure on the uncanny valley phenomenon by using mixed-effects modelling with partially  crossed random effects_  (advisors: Markus Appel, Tanja Lischetzke)
 
<br/><br/>

## <i class="bi bi-pen-fill"></i> Teaching Experience

**Writing APA-Style Manuscripts in R**, University of Mannheim , RTG Statistical Modeling in Psychology (level: P.hD.; language: English)

**Introduction to Shiny**, University of Mannheim , RTG Statistical Modeling in Psychology (level: P.hD.; language: English)

**Introduction to lab.js**, University of Mannheim , RTG Statistical Modeling in Psychology (level: P.hD.; language: English)

**G3 Seminar: Cognitive Illusions**, University of Mannheim, Department of Experimental Psychology (level: Bachelor; language: German)

**Experimental Internship**, University of Mannheim, Department of Experimental Psychology (level: Bachelor; language: German)

**Workshop Advanced R**, University of Mannheim , RTG Statistical Modeling in Psychology (level: P.hD.; language: English)

**Workshop Modern R**, University of Mannheim , RTG Statistical Modeling in Psychology (level: P.hD.; language: English)

**Tutorial Multivariate Statistics**, University of Cologne , Department for Research Methods and Experimental Psychology (level: M.Sc.; language: German)

**Tutorial Multivariate Statistics**, University of Cologne , Department for Research Methods and Experimental Psychology (level: M.Sc.; language: German)
 
**Tutorial Data Collection and Analysis**, University of Cologne , Department for Research Methods and Experimental Psychology  (level: M.Sc.; language: German)

**Tutorial Empirical Internship**, University of Koblenz-Landau, Department for Methods and Evaluation (level: B.Sc.; language: German)

**Workshop Introduction to R**, University of Koblenz-Landau, Department for Methods and Evaluation (level: P.hD.; language: English)

**Tutorial Test Theory with R**, University of Koblenz-Landau, Department for Methods and Evaluation (level: B.Sc.; language: German)

<br/><br/>

## <i class="bi bi-graph-up"></i> Programming and statistics


Languages: Mastery of R. Regular practice writing JAGS and Stan for Bayesian modeling, as well as HTML/CSS and JavaScript to program experiments. I also did some courses in and analysis with Python. Exposure to C++.

Computing tools and technologies: tidy data and the R tidyverse, git and GitHub, knitr/rmarkdown/Quarto, Shiny.

Statistics: Regression: generalized linear models, hierarchical and mixed effects models, and Bayesian versions of these models. Structural equation modeling and factor analysis. Neural networks:  familiarity with how some deep network architectures work. 

Experimental software: nowadays mostly lab.JS and Soscisurvey. Some experience with OpenSesame and  Inquisit.

<br/><br/>

## <i class="bi bi-building"></i> University Service


**Elected Ph.D. students Spokesperson**, since 2020, Research Training Group Statistical Modeling in Psychology, University of Mannheim

<br/><br/>

## <i class="bi bi-ui-radios"></i> Reviewing

Ad-hoc reviewer:  Computers in Human Behaviour, Judgment and Decision Making

<br/><br/>

## <i class="bi bi-card-list"></i> Professional Memberships

[German Psychological Society](https://www.dgps.de/) (DGPs) Sections *Methods and Evaluation* and *General Psychology*

<br/><br/>

## <i class="bi bi-gear-fill"></i> Workshops and Summerschools


### 2019 

**Introduction to Stan: A Probabilistic Programming Language for Bayesian Inference**, Workshop by Paul Bürkner, 2019, at University of Mannheim, Germany 

**An Introduction to Machine Learning**, Workshop by Andreas Brandmeaier, 2019, at University of Mannheim, Germany 

**NHST reloaded: Recent developments**, Workshop by Rolf Ulrich and Jeff Miller, 2019, at University of Tübingen, Germany 

**Model-based Neuroscience**, Summer School, 2019, at University of Amsterdam, Netherlands

**A Modern Axiomatic Perspective: Theory, Statistical Methodology, and Experimental Design**, Workshop by Clintin Davis-Stober, 2019, at University of Mannheim, Germany

**Python basics**, Workshop by Stefan Radev, 2019, at University of Heidelberg, Germany

**Hypothesis Evaluation Using the Bayes Factor**, Workshop by Herbert Hoijtink, 2019, at University of Mannheim, Germany

**Introduction to Bayesian Inference: Core Principles and Application in Stan**,  Workshop by Daniel Heck, 2019, at University of Mannheim, Germany

**Numerical Methods for Quantitative Psychologists**, Workshop by Francis Tuerlinckx, 2019, at University of Tübingen, Germany

**Academic Writing and Publishing**, Workshop by Benjamin Hilbig, 2019, at University of Koblenz-Landau, Germany

### 2018

**An Introduction to modern R, Statistical Modeling, and Mixed Models**, Workshopy by Henrik Singmann, 2018, at University of Freiburg, Germany

**Advanced Topics in R**, Workshopy by Daniel Heck, 2018, at University of Mannheim, Germany

**Analysis of Response Time**, Workshopy by Trisha van Zandt, at University of Mannheim, Germany

**Rules of Good Scientific Practice**, Workshop by Arndt Bröder, 2018, at University of Mannheim, Germany

### 2014

**Structural equation modelling in R with lavaan**, Workshop by Dorota Reis & Tanja Lischetzke, 2014, University of Koblenz-Landau, Germany




