---
title: "Teaching"
---

<br>

## Workshops (PhD level)

**Writing APA-Style Manuscripts in R**: This workshop teaches the basics of LaTeX, R Markdown and the `papaja`-package to enable participants to write APA conform manuscripts in R. [[Materials](https://github.com/dizyd/Writing-Manuscripts-in-R-Markdown-LaTeX-Papaja)]

**Introduction to Shiny**: This workshop gives a basic introduction into building interactive web applications in R with `shiny` and covers topics of inputs, outputs, layout, reactivity and much more. [[Materials](https://github.com/dizyd/Introduction-to-Shiny-R)]

**Introduction to lab.js**: This workshop teaches the basics of of [`lab.js](https://lab.js.org/), a free, open, online study builder for the behavioral and cognitive sciences.  Participants learn to create their own experiments using the builder GUI, HTML, CSS and JavaScript.

**Advanced R**: This workshop shows how to benchmark and profile functions in R to identify potential bottlenecks. The workshops then also shows how to  solve those bottlenecks and speed up your R code through vectorized R code, Rcpp, or parallelization. [[Materials](https://github.com/dizyd/Workshop_AdvancedR)]
 
**Modern R**: This workshop teaches the basics of R Markdown and how to write APA conform manuscripts using R Markdown and the `papaja`-package. In addition, it will give an introduction into building interactive web applications in R with `shiny`.  [[Materials](https://github.com/dizyd/Workshop_ModernR)]


## Seminars (Bachelor)


**General Psychology II**: Topics: Cognitive Illusions.


**Project Seminar - Experimental Psychology**: In this seminar, students plan, conduct, and present their own research project in small groups. Projects supervised so far: 

- Differences of Mouse-Trajectories in Similarity Ratings. 
- Testing the Spatial Arrangement Method (SpAM) to measure similarity.
- Does the News Reporting of COVID-19 Influence Decision Making ?
- Framing Effect in Times of a Pandemic: Disease or Risk ? 
